---
title: "Day 15: Multivariate"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(pdxTrees)
library(tidyverse)
library(ggraph)
library(igraph)
library(ellipse)
library(RColorBrewer)
```


```{r data}
park_trees <- get_pdxTrees_parks()

treecount <- count(park_trees, Family) %>%
  arrange(desc(n)) %>%
  top_n(10)

top_trees <- treecount$Family

my_trees <- park_trees %>%
  filter(Family %in% top_trees) %>%
  add_count(Family, Genus) %>%
  filter(n > 30) %>%
  add_count(Genus, Species) #%>%
  #filter(nn > 30)
```


```{r}
set1 <- my_trees %>%
  mutate(from = "origin") %>%
  select(from, Family) %>%
  distinct() %>%
  rename("to"="Family")
  
set2 <- my_trees %>%
  select(Family, Genus) %>%
  distinct() %>%
  rename("from"="Family", "to"="Genus")

set3 <- my_trees %>%
  select(Genus, Species) %>%
  distinct() %>%
  rename("from"="Genus", "to"="Species")

hierarchy <- rbind(set1, set2, set3)
vertices <- data.frame(name = unique(c(as.character(hierarchy$from), as.character(hierarchy$to))) ) 

mygraph <- graph_from_data_frame( hierarchy, vertices=vertices )
```



```{r}
plot(mygraph, vertex.label="", edge.arrow.size=0, vertex.size=1)

ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_link(alpha=.5) +
  theme_void()
 
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal(alpha=.5) +
  theme_void()

ggraph(mygraph, 'dendrogram') + 
  geom_edge_diagonal(alpha=.5, strength=1) +
  theme_void()
```



