---
title: "Day 8: Animals"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

```{r libraries}
library(tidyverse)
library(palmerpenguins)
library(see)
library(Hmisc)
library(showtext)
```

```{r add font}
font_add_google("Lora", "lora")
showtext_auto(enable=TRUE)
```

```{r load data}
#from palmerpenguins
penguins <- penguins
```

```{r bill length, warning=FALSE, dpi=400}
ggplot(penguins, aes(x=species, y=bill_length_mm, fill=species))+
  geom_violinhalf() +
  geom_dotplot(binaxis = "y", stackdir = "down", 
               dotsize=.4, position = position_nudge(-0.025))+
  theme_modern() +
  stat_summary(fun.data = mean_sdl, 
               fun.args = list(mult = 1), 
               geom = "pointrange", 
               position = position_nudge(0.05)) +
  scale_fill_manual(values=c("#9fb69b", "#f7cfad", "#e8867c"))+
  theme(text=element_text(family = "lora"))+
  labs(y="bill length (mm)")

##file = group2-distributions/images/8_bill_length.png
```

```{r body mass, warning=FALSE, dpi=400}
ggplot(penguins, aes(x=species, y=body_mass_g, fill=species))+
  geom_violinhalf() +
  geom_dotplot(binaxis = "y", stackdir = "down", 
               dotsize=.4, position = position_nudge(-0.025))+
  theme_modern() +
  stat_summary(fun.data = mean_sdl, 
               fun.args = list(mult = 1), 
               geom = "pointrange", 
               position = position_nudge(0.05)) +
  scale_fill_manual(values=c("#9fb69b", "#f7cfad", "#e8867c"))+
  theme(text=element_text(family = "lora"))+
  labs(y="body mass (g)")

##file = group2-distributions/images/8_body_mass.png
```

